### ISSUE TITLE
Some of the links to products in the Intro section are broken...

### ISSUE THREAD

**Issue by deftdawg** [zackbradys/rancher-effortless#1]
Neat presentation, just checking out your github and noticed Neuvector and a couple other links go to 404s.

I was able to find them, so no biggie.

:beers:

**Comment by zackbradys** [comment]
Thanks for the heads up @deftdawg! I'll double check the links.

**Comment by zackbradys** [comment]
closed fixed under commit #[a1b66ba](https://github.com/zackbradys/rancher-effortless/commit/a1b66bab8ff501dcd2c8f35aedd9d6c1657265e9)
