### ISSUE TITLE
Failed to create symbolic link

### ISSUE THREAD

**Issue by cysecnoob** [zackbradys/rancher-effortless#2]
New to all of this so thanks for the tutorials! Noticed your code is missing 'source ~/.bashrc'. 

# server(s): rke2-cp-01
# Symlink kubectl and containerd
sudo ln -s /var/lib/rancher/rke2/data/v1*/bin/kubectl /usr/bin/kubectl
sudo ln -s /var/run/k3s/containerd/containerd.sock /var/run/containerd/containerd.sock

# Update and Source BASHRC
cat << EOF >> ~/.bashrc
export PATH=$PATH:/var/lib/rancher/rke2/bin:/usr/local/bin/
export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
export CRI_CONFIG_FILE=/var/lib/rancher/rke2/agent/etc/crictl.yaml
alias k=kubectl
EOF
-->source ~/.bashrc
# Verify RKE2 is Running/Ready
kubectl get nodes

**Comment by zackbradys** [comment]
Thank you and thank you for the good catch! Called out in the title, but not in the code...

I will get this updated later today!

**Comment by cysecnoob** [comment]
Great! Also, I'm having a bit of trouble with neuvector. The code is also different from the video, and I get 'controller is not available' when trying to access the webUI. Any suggestions?

**Comment by zackbradys** [comment]
Closing as resolved per https://github.com/zackbradys/rancher-effortless/commit/171e426cf64f3d1712c5ae8e422a6fc58fdb28f8!
